# Generated by Django 6.0.3 on 2026-06-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(max_length=50000, verbose_name='正文')),
                ('summary', models.CharField(blank=True, default='', max_length=500, verbose_name='摘要')),
                ('cover_image', models.URLField(blank=True, default='', max_length=255, verbose_name='封面图片URL')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('taken_down', '已下架'), ('archived', '已归档')], default='draft', max_length=15, verbose_name='状态')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除（软删除）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='分类描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '文章分类',
                'verbose_name_plural': '文章分类',
                'db_table': 'categories',
                'ordering': ['id'],
            },
        ),
    ]
